### ISSUE TITLE
Solve flip of death

### ISSUE THREAD

**Issue by galeots** [thogue95/MultiWii#1]
Hi
firmware created also solves the flip of death?
that improvements are there?

**Comment by hsiboy** [comment]
The so called flip of death is caused by the way in which the runner 250 is configured.
It is caused by the motors stopping when the throttle drops below ~7%. When this happens and the pilot tries to compensate by increasing the throttle, the front ESCs often respond first causing the quad to flip.
You can make the quad flip while on the ground by quickly "banging" the throttle.
MultiiWii can be configured to make the motors just spin (idle) on arming, but most people have used trim on the throttle to compensate.
It's a matter of taste. Have the motor stop below 900 or have them idle.
But yes, you can configure this fork of multiwii to mitigate flips caused by low throttle motor stall.

Improvement include all the features of Multiwii 2.4 which includes waypoints (if you have GPS).

**Comment by thogue95** [comment]
The flip of death is a bit more complex than just having a misconfigured throttle.  As I was porting the code, I came across significant differences in the sensor wave patterns, when viewed on MW GUI, between the factory firmware and the MultiWii 2.4.  The only way I could get the patterns the same is to lower the GYRO_LPF down to 10Hz.  After much tuning and testing, I had come to realize that this is most likely the root cause of the problems people are seeing with the factory firmware.  I have not had a FOD event since I have been running MW 2.4 and yes I do make sure that my motors spin when armed just as hsiboy suggests.  Oh...as for motors spinning at different times, this is mitigated by running the calibration routine as described in the config.h file and setting MINTHROTTLE.

**Comment by galeots** [comment]
@thogue95  then you have solved the problem of porting?

**Comment by thogue95** [comment]
If you meant to say that the FOD problem is solved in the firmware, then my answer is that it is that I have not seen the FOD while using the new version of firmware.  You still need to make sure the motors spin while armed to the point before the quadcopter lifts.  Before the new firmware, my quadcopters would not hover and would crash before the battery ran out.  Now they fly great and now when they do crash I know it was something I did.  Oh...one more important thing, you can also "Trim" the accelerometers which really helps to make it stable in flight.   Make sure you know how to replace the boot loader on the Atmel 2560 as that will need to be done before you can download new code to the flight controller.

**Comment by Pino74** [comment]
https://www.youtube.com/watch?v=kxRgi_RW0V0

**Comment by thogue95** [comment]
@Pino74  Without any other information that what is in your video, it looks like you might have a bad power distribution board.  Probably a bad solder connection or a cracked trace.  You can try asking on the Walkera Forums http://walkeraforums.com/ or on the Walkera 250 Support Facebook page  https://www.facebook.com/groups/runner250support/

I am also guessing that you have the original firmware on the quadcopter

**Comment by Pino74** [comment]
Hi,No other information is available , because ' it is pure engine shutdown, the runner for the rest and ' perfect , no injury or false contacts , esc pdb etc , and when there ' the trim on the radio, the problem is not out.I did systematic evidence ,

**Comment by Pino74** [comment]
if I try to accelerate leaving the drone on the table , without him simulate the flight, without trim , the drone never turn off the engines , you have to simulate the movements , and there ' a movement that can not stand the drone and ' that of gravity ' , what almost always does ' off the engines , while at the same time I accelerate and then bring the gas to zero , does not turn on after more' , I find myself unarmed engines

**Comment by thogue95** [comment]
After the engines shut off, can you re-arm the motors and have them spin up without unplugging the batteries?

**Comment by Pino74** [comment]
I repeat test the drone of a stationary table with trim to zero and ' a false test must simulate the movements and bring gas to zero , suddenly you find yourself magically unarmed engines , again I say if the drone remains firm on the table , can accelerate and bring gas to zero a thousand times , the engines never go out

**Comment by Pino74** [comment]
yes i can arm without unplug the batteries....also 5 sec,,,it re arm to soon....

**Comment by thogue95** [comment]
Go post on the facebook link and I will comment there.  More people will also help with the problem.  
I would like to keep this page for comments on the firmware and source code discussion.

**Comment by Pino74** [comment]
I even bought your book if you are the author , I am a electronics technician , but I have no experience in this area , do anything but work, but when I can I follow

**Comment by thogue95** [comment]
Do you have the new firmware on the Runner or Walkera firmware?  You want to determine if the controller is rebooting when the motor stops.

**Comment by Pino74** [comment]
if you want your firmware no, I bought directly a main cc3d hoping that that does not suffer from that problem , and then I saw that the procedure and ' long and it takes the adapter and then after I will use not ' more ' , but' the I was thinking of updating

**Comment by Pino74** [comment]
now i have walkera 1.2 firmware

**Comment by thogue95** [comment]
Can you confirm that you have the 250(r) controller and the Walkera firmware when the problem occurs?

**Comment by Pino74** [comment]
certainly, but jokes ?Walkera firm shit i have

**Comment by Pino74** [comment]
The thing I do not like and that in addition to having used a hardaware old and already had problems on that platform , they then after just added a barometer and inherited problems , so walkera and ' informed and in my opinion are hardware problems that' change walkera main and pretends not to understand

**Comment by Pino74** [comment]
another thing I do not like and that walkera in dowload section has not released any of the bug fixes known together with the firm 1.2 and that makes me ' suspect , usually even the most' lack of updates, even if you update a lighter, there 's always a fix known and resolved problems and improvements

**Comment by thogue95** [comment]
I think your problem maybe physical.  Disconnect and reconnect the ribbon cable for the flight controller and make sure the flight controller is firmly attached to the board.  

I think it is okay to have used hardware.  It is just parts and software.  I have bought used ones and they work.  Those motions you are making are strong enough to make a poor ribbon connection have problems. Yes...Walkera support is crazy frustrating.  I suggest you try your test when connected to MultiWii GUI.  Try to video record the screen when you do it.  I am interested in the sensor wave patterns.

**Comment by Pino74** [comment]
the cable and ' in its place , and ' integrity I have already ' checked and a true flight not ' less stressful of my movements for the cable , tomorrow if I have time I will show us that I can simulate shutdown even in a more ' gentle, do not be confused by the fact that it took strength and speed , then I'll show you that even in a gentle way I can

**Comment by thogue95** [comment]
Definitely put it on MultiWii GUI and observe the waveforms. Looking for abnormal conditions.

**Comment by Pino74** [comment]
if it was the cable when I was the trim to 7 % on the radio was shut down again

**Comment by Pino74** [comment]
while with trim to 7% on the radio I can make him do anything I want , I can really high stress both in flight and at home without propellers , never goes , but just never , as a port to zero trim , randomly , but always with movements of the drone , turns off

**Comment by Pino74** [comment]
I salute you go to bed , you soon and thanks

**Comment by thogue95** [comment]
Discussion has been moved to the Facebook page

**Comment by hsiboy** [comment]
I suspect you are going to attract a lot of questions and venting and gnashing and wailingTom.

It may be a good idea to update the readme.md with links to relevant forums etc.

Stuart

**Comment by thogue95** [comment]
good idea.  I feel bad for people going through the same frustrations that I did.  

```
On Monday, August 22, 2016 12:56 PM, stuart taylor <notifications@github.com> wrote:
```

 I suspect you are going to attract a lot of questions and venting and gnashing and wailingTom.It may be a good idea to update the readme.md with links to relevant forums etc.Stuart—

**Comment by Pino74** [comment]
i cant see the discussion

2016-08-22 22:16 GMT+02:00 thogue95 <notifications@github.com>:

> good idea.  I feel bad for people going through the same frustrations that
> I did.
>
>
> On Monday, August 22, 2016 12:56 PM, stuart taylor <

**Comment by thogue95** [comment]
I had closed it because we were working the issue on the Facebook post.  I think you may have found a bug in the Walkera code so it would be great if we got someone on the Facebook page to duplicate your test and confirm it.  One thing to check is to do your test on MultiWii GUI to see if the Devo 7 is sending strange signals.

**Comment by Pino74** [comment]
whree i follow now the discussion?i am confused....

2016-08-22 22:51 GMT+02:00 thogue95 <notifications@github.com>:

**Comment by Pino74** [comment]
my test easy to repeat , so just be patient , the defect zero trim comes out , just bind  radio and  the drone without propellers and put playing with the gas, and at the same time move the drone , after a while ' it comes out .
